// <auto-generated />
namespace Rent_a_Car.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedaddressforusers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedaddressforusers));
        
        string IMigrationMetadata.Id
        {
            get { return "201906221527005_added address for users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
